### ISSUE TITLE
Create PostgreSQL Database Connection

### ISSUE THREAD

**Issue by not-Boris** [G12-hc/tako-chart#10]
Description: As a developer, I want to connect from a PostgreSQL database in python to prepare it for querying in the backend.

Acceptance Criteria:
1. Stable connection and authorisation to a postgreSQL database written in Python using Psycopg3
2. Possible to query database in Python backend

**Comment by not-Boris** [comment]
Completed in #21

**Comment by crazybrain23** [comment]
> Completed in #21

Technically you shouldn't close this until #21 is merged.
(also there are keywords that can be put in PRs to auto close issues https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

**Comment by Jake-Andrews-git** [comment]
using psycopg2 not 3

**Comment by crazybrain23** [comment]
> using psycopg2 not 3

Why 2? The documentation says to use 3 for new projects because 2 is no longer being updated.
> [Psycopg 3](https://pypi.org/project/psycopg/) is the evolution of psycopg2 and is where [new features are being developed](https://www.psycopg.org/psycopg3/docs/index.html): if you are starting a new project you should probably start from 3!

**Comment by Jake-Andrews-git** [comment]
I couldn't get 3 working with it, I will try again tomorrow
