### ISSUE TITLE
Visualise Bar Chart of File Sizes (Line Count per File)

### ISSUE THREAD

**Issue by not-Boris** [G12-hc/tako-chart#13]
Description: As a user, I want a bar chart of file sizes to identify disparities in individual file sizes within the project.

Acceptance Criteria:
1. File size data is retrieved from the PostgreSQL database.
2. The histogram displays the distribution of file sizes.
3. The visualization is responsive and clear across devices.

**Comment by Jake-Andrews-git** [comment]
Impossible task as I can't return file size since there is no field in the database, despite it existing, I can't store file size and route it to the front end. I can create a new field which is not advised, unsure what to do otherwise to assist this issue.

**Comment by not-Boris** [comment]
Changed issue scope from file byte size to file line count, to make this a possible task, ready to pick up

**Comment by not-Boris** [comment]
Can attempt to make histogram, but consensus is may look messy

**Comment by not-Boris** [comment]
Merged in #43
