### ISSUE TITLE
Finalise API 

### ISSUE THREAD

**Issue by not-Boris** [G12-hc/tako-chart#23]
As a front-end developer, I want to access an API in order to make visualisations of data on a webpage

Acceptance Criteria
- Relevant data included in API

**Comment by not-Boris** [comment]
Done in [4aab224](https://github.com/G12-hc/ro-visualisation/commit/4aab22405773c0eca05a16bbb04de21dd8316ff5)

**Comment by crazybrain23** [comment]
API is missing endpoint for all repos, #31 will fix.
