### ISSUE TITLE
Website Design Wireframes

### ISSUE THREAD

**Issue by not-Boris** [G12-hc/tako-chart#3]
Create Website Wireframes, use sketches or digital mockups of desired website design. These will be sent to the client for confirmation.

**Comment by xdLouAyy** [comment]
![Image](https://github.com/user-attachments/assets/e150a3ce-be59-47dc-8397-9cce7c791e19)

Google Docs Link to Edit -> https://drive.google.com/file/d/15nQhh2pv8PTns4aRUQIPZ9cwNokfSDA4/view?usp=sharing

**Comment by not-Boris** [comment]
Moved to Done. Closing.
