### ISSUE TITLE
Restructure API endpoints

### ISSUE THREAD

**Issue by crazybrain23** [G12-hc/tako-chart#33]
Currently `/repos/` returns all the repos, but `/repo_data/{id}` is how you access that data.
I propose that `/repos/{id}` is the data endpoint to match with `/repos` for getting the repos.

If @not-Boris wants to create a story for this or something?

**Comment by not-Boris** [comment]
As a developer, I want to have simple API endpoints in order to easily understand the structure of the backend and implement charts intuitively.

Acceptance Criteria:
- Naming scheme for API changes to be more intuitive

**Comment by Jake-Andrews-git** [comment]
resolved in #34
