### ISSUE TITLE
Repository Comparison Page 

### ISSUE THREAD

**Issue by not-Boris** [G12-hc/tako-chart#52]
As a user, I want to be able to compare graphs and metrics between repositories in order to understand the differences.

Acceptance Criteria:
- Graphs in parallel
- MOST/LEAST tables
- Logical differences in metrics
  - Difference in extension types
  - Difference in amount of contributors
  - etc.

**Comment by xdLouAyy** [comment]
![Image](https://github.com/user-attachments/assets/19b0f1c8-ab4b-41ed-9e7f-ae2fefb28a90)

To edit or make changes to the compare page wireframe yourself follow the link: https://drive.google.com/file/d/1mUXp57qvacPCkqPEGyFcMDYMkeRnGcYE/view?usp=sharing

**Comment by not-Boris** [comment]
Donezo in #77
