### ISSUE TITLE
Management of Repositories

### ISSUE THREAD

**Issue by not-Boris** [G12-hc/tako-chart#66]
As a user, I want to be able to manage (add/remove) repositories in order to view details and remove old repositories

Acceptance Criteria:
- Remove Repos
- Add Repos
- View Repos

**Comment by xdLouAyy** [comment]
![Image](https://github.com/user-attachments/assets/f58ecd2a-2b55-4247-9467-afe8e8122242)

If you find any issues with the wireframe or want to make manual changes, please follow the following google docs link:

https://drive.google.com/file/d/1mUXp57qvacPCkqPEGyFcMDYMkeRnGcYE/view?usp=sharing

**Comment by crazybrain23** [comment]
@celie2 said they'd add endpoints support for update and delete

**Comment by ghost** [comment]
we don't need an endpoint for update, that's already done in the fetch-repo endpoint (and i'll add support for that to the update button)

deletion however is indeed still missing an endpoint

**Comment by ghost** [comment]
done in 5d3af2939cfed7d5ae5c94267c23d8e4c58785c9
