### ISSUE TITLE
Research and Review Technologies

### ISSUE THREAD

**Issue by not-Boris** [G12-hc/tako-chart#7]
Research visualisation libraries and python libraries to use, along with any other relevant technologies if required.

**Comment by ghost** [comment]
## Frontend
[Bootstrap](https://getbootstrap.com/) as a frontend toolkit

### Data visualisation
- [D3](https://d3js.org/)
  - very high-quality, but likely too low-level to be suitable for us
- [Plotly.js](https://plotly.com/javascript/)
  - seems suitably high-level
  - has all the chart types mentioned in the brief
  - but is pretty massive (~1.3 MB minified and gzipped!)
- [Chart.js](https://www.chartjs.org/docs/latest/)
  - Seems good and high-level enough, **but** doesn't have built-in histogram type!
    - people seem to emulate histograms with bar charts with Chart.js, but that's not ideal

Verdict: let's go with Plotly.js

## Backend technologies

All the backend needs to do is serve static assets (HTML, JS, etc.), and respond to a request from the frontend to send data. For our very simple purposes [FastAPI](https://fastapi.tiangolo.com/) should be more than enough, along with [psycopg2](https://www.psycopg.org) to talk to the PostgreSQL database.
